# Generated by Django 3.2.24 on 2024-04-04 09:40

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('news_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('short_description', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
