# Generated by Django 3.2.24 on 2024-04-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
