# Generated by Django 3.2.24 on 2024-04-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
