# Generated by Django 3.2.24 on 2024-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(max_length=250),
        ),
    ]
