# Generated by Django 3.2.24 on 2024-03-23 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20240323_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size_quantity_available',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
